'use client';
import { useMemo, useState } from 'react';
import { LayoutDashboard, Users, ChartNoAxesCombined, MessageSquare, ArrowUpRight, SlidersHorizontal, RotateCcw, ChevronDown, X, MousePointer2, CalendarDays, Info, Search, ArrowRight } from 'lucide-react';
import survey from '../data/survey.json';

type RecordRow = typeof survey.records[number];
type Field = 'status' | 'research' | 'information' | 'channel' | 'importance' | 'barrier' | 'content';
const rows = survey.records;
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
const names: Record<Field,string> = {status:'Status',research:'Riset perusahaan',information:'Informasi',channel:'Kanal',importance:'Skor kepentingan',barrier:'Hambatan',content:'Konten'};
const short: Record<string,string> = {
 'Peserta Magang / Internship':'Peserta magang', 'Fresh Graduate (sedang mencari kerja / melamar)':'Fresh graduate', 'Mahasiswa Tingkat Akhir':'Mahasiswa tingkat akhir', 'Karyawan / Management Trainee':'Karyawan / MT',
 'Instagram perusahaan / akun employer branding':'Instagram', 'LinkedIn perusahaan':'LinkedIn', 'Website resmi perusahaan':'Website resmi',
 'Informasi posisi dan pekerjaan':'Posisi & pekerjaan', 'Budaya kerja / workplace culture':'Budaya kerja', 'Profil dan pengalaman karyawan':'Profil & pengalaman karyawan', 'Nilai dan identitas perusahaan':'Nilai & identitas perusahaan',
 'Lebih banyak membahas produk/perusahaan daripada kehidupan karyawan':'Lebih banyak membahas produk / perusahaan', 'Jarang memperlihatkan aktivitas sehari-hari karyawan':'Minim aktivitas sehari-hari karyawan',
 'Pengalaman onboarding / menjadi karyawan baru':'Pengalaman onboarding', 'Informasi mengenai career development':'Career development', 'Aktivitas team / employee engagement':'Aktivitas tim / engagement'
};
const label=(s:string)=>short[s]||s;
const values=(r:RecordRow,f:Field):string[]=>Array.isArray(r[f])?r[f] as string[]:[String(r[f])];
const options=(f:Field)=>[...new Set(rows.flatMap(r=>values(r,f)))];
const percent=(n:number,d:number)=>d?Math.round(n/d*100):0;
const colors=['#ed1c24','#242529','#8c8d94','#d4d4d8'];
function count(data:RecordRow[],f:Field){return options(f).map(name=>({name,count:data.filter(r=>values(r,f).includes(name)).length})).sort((a,b)=>b.count-a.count);}

export default function Dashboard(){
 const [filters,setFilters]=useState<Partial<Record<Field,string>>>({});
 const [view,setView]=useState('Ringkasan');
 const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [query,setQuery]=useState('');
 const [method,setMethod]=useState(false);
 const toggle=(field:Field,value:string)=>setFilters(old=>{const next={...old};if(next[field]===value)delete next[field];else next[field]=value;return next;});
 const filtered=useMemo(()=>rows.filter(r=>Object.entries(filters).every(([f,v])=>values(r,f as Field).includes(v!))&&(!start||r.date.slice(0,10)>=start)&&(!end||r.date.slice(0,10)<=end)),[filters,start,end]);
 const reset=()=>{setFilters({});setStart('');setEnd('');setQuery('');};
 const n=filtered.length, ratings=filtered.filter(r=>r.importance!==null), avg=ratings.length?ratings.reduce((s,r)=>s+(r.importance||0),0)/ratings.length:0;
 const channels=count(filtered,'channel'), statuses=count(filtered,'status'), research=filtered.filter(r=>r.research==='Ya').length;
 const active=Object.keys(filters).length+Number(!!start)+Number(!!end);
 const tabs=[{name:'Ringkasan',icon:LayoutDashboard},{name:'Profil responden',icon:Users},{name:'Eksplorasi jawaban',icon:ChartNoAxesCombined},{name:'Suara responden',icon:MessageSquare}];
 function Bars({field,title,subtitle,compact=false}:{field:Field,title:string,subtitle:string,compact?:boolean}){const entries=count(filtered,field);return <section className="panel"><div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="question-tag">Q{({information:3,channel:4,barrier:6,content:7,status:1,research:2,importance:5})[field]}</span></div><div className={'bars '+(compact?'compact':'')}>{entries.map((e,i)=><button key={e.name} className={'bar-row '+(filters[field]===e.name?'selected':'')} onClick={()=>toggle(field,e.name)} aria-pressed={filters[field]===e.name} title={`${e.name}: ${e.count} responden (${percent(e.count,n)}%). Klik untuk filter.`}><div className="bar-label"><span>{label(e.name)}</span><span><b>{e.count}</b><small>{percent(e.count,n)}%</small></span></div><div className="track"><div style={{width:`${percent(e.count,n)}%`,background:i===0||filters[field]===e.name?'#ed1c24':'#333438'}}/></div></button>)}</div><div className="chart-note"><MousePointer2 size={13}/> Klik batang untuk memfilter seluruh dashboard</div></section>}
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><img src={`${basePath}/bridgestone-white.png`} alt="Bridgestone"/><span>PEOPLE & CULTURE</span></div><div className="workspace-label">WORKSPACE</div><nav>{tabs.map(({name,icon:Icon})=><button key={name} className={view===name?'nav-active':''} onClick={()=>setView(name)}><Icon size={19}/><span>{name}</span>{view===name&&<span className="nav-dot"/>}</button>)}</nav><div className="side-bottom"><img src={`${basePath}/e8-white.png`} alt="Bridgestone E8 Commitment"/><p>Empowering people.<br/>Shaping the journey.</p><div className="side-rule"/><span>EMPLOYER BRANDING SURVEY</span><small>September 2026</small></div></aside>
  <main><header className="topbar"><div className="breadcrumb">People & Culture <span>/</span> <b>Employer branding</b></div><div className="top-right"><span className="source-badge">Excel data</span><div className="avatar">HR</div></div></header>
  <div className="main-content"><div className="page-title"><div><div className="eyebrow">SURVEY ANALYTICS <span>2026</span></div><h1>Employer Branding <span>Insights</span></h1><p>Memahami apa yang dicari talenta, sebelum mereka memilih bergabung.</p></div><button className="outline-button" onClick={()=>setMethod(true)}><Info size={16}/> Tentang data</button></div>
   <div className="filterbar"><div className="filter-title"><SlidersHorizontal size={17}/><b>Filter data</b></div><label className="select-wrap"><span className="sr-only">Status responden</span><select value={filters.status||''} onChange={e=>setFilters(p=>{const v={...p};if(e.target.value)v.status=e.target.value;else delete v.status;return v;})}><option value="">Semua status responden</option>{options('status').map(s=><option key={s} value={s}>{label(s)}</option>)}</select><ChevronDown size={14}/></label><div className="date-filters"><CalendarDays size={16}/><input aria-label="Tanggal mulai" type="date" value={start} onChange={e=>setStart(e.target.value)} min="2026-09-17" max="2026-09-21"/><span>—</span><input aria-label="Tanggal akhir" type="date" value={end} onChange={e=>setEnd(e.target.value)} min="2026-09-17" max="2026-09-21"/></div><button className="reset" onClick={reset}><RotateCcw size={15}/> Reset filter</button></div>
   {active>0&&<div className="active-filters"><span>{n} dari {rows.length} respons</span>{Object.entries(filters).map(([f,v])=><button key={f} onClick={()=>toggle(f as Field,v!)}>{names[f as Field]}: {label(v!)} <X size={13}/></button>)}{(start||end)&&<button onClick={()=>{setStart('');setEnd('');}}>Tanggal: {start||'awal'} – {end||'akhir'} <X size={13}/></button>}</div>}
   <div className="section-heading"><h2>{view}</h2><span><span className="little-dot"/>17–21 September 2026</span></div>
   <div className="kpis"><article className="kpi primary"><div><span>Total responden</span><Users size={19}/></div><strong data-testid="respondent-count">{n}<small>orang</small></strong><p>{active?'Sesuai filter yang dipilih':'Seluruh respons survei'}</p><div className="kpi-decor"/></article><article className="kpi"><div><span>Melakukan riset perusahaan</span><Search size={18}/></div><strong>{n?percent(research,n):'—'}<small>%</small></strong><p>{research} dari {n} responden menjawab “Ya”</p></article><article className="kpi"><div><span>Pentingnya budaya kerja</span><ChartNoAxesCombined size={19}/></div><strong>{ratings.length?avg.toFixed(2).replace('.',','):'—'}<small>/ 5</small></strong><p>Rata-rata skor kepentingan · Q5</p></article><article className="kpi"><div><span>Kanal paling banyak dipilih</span><ArrowUpRight size={19}/></div><strong className="channel-value">{n?label(channels[0].name):'—'}</strong><p>{n?`${channels[0].count} responden · ${percent(channels[0].count,n)}% dari pilihan saat ini`:'Belum ada respons'}</p></article></div>
   {!n?<div className="empty"><Search size={32}/><h2>Tidak ada respons yang cocok</h2><p>Coba ubah kombinasi filter untuk melihat data lainnya.</p><button className="red-button" onClick={reset}>Reset semua filter</button></div>:<>
   {(view==='Ringkasan'||view==='Profil responden')&&<div className="overview-grid"><section className="panel"><div className="panel-head"><div><h2>Siapa responden kita?</h2><p>Komposisi berdasarkan status saat ini</p></div><span className="question-tag">Q1</span></div><div className="donut-layout"><div className="donut"><svg viewBox="0 0 200 200" role="img" aria-label="Komposisi status responden">{statuses.map((s,i)=>{const prev=statuses.slice(0,i).reduce((a,v)=>a+v.count,0);return <circle key={s.name} cx="100" cy="100" r="77" fill="none" stroke={colors[i]} strokeWidth="25" strokeDasharray={`${Math.max(0,s.count/n*483.8-3)} ${483.8}`} strokeDashoffset={-prev/n*483.8} transform="rotate(-90 100 100)" onClick={()=>toggle('status',s.name)}><title>{`${label(s.name)}: ${s.count}`}</title></circle>})}</svg><div className="donut-center"><strong>{n}</strong><span>responden</span></div></div><div className="legend">{statuses.map((s,i)=><button key={s.name} aria-pressed={filters.status===s.name} onClick={()=>toggle('status',s.name)}><i style={{background:colors[i]}}/><span>{label(s.name)}<small>{percent(s.count,n)}% dari responden</small></span><b>{s.count}</b></button>)}</div></div><div className="chart-note"><MousePointer2 size={13}/> Klik segmen atau legenda untuk memilih status</div></section><Bars field="channel" title="Di mana talenta mencari informasi?" subtitle="Kanal yang digunakan · jawaban pilihan ganda" compact/></div>}
   {(view==='Ringkasan'||view==='Eksplorasi jawaban')&&<div className="two-col"><Bars field="information" title="Informasi yang paling dicari" subtitle="Hal yang dicari sebelum melamar · pilihan ganda"/><Bars field="barrier" title="Hambatan menemukan informasi" subtitle="Kendala saat menjelajahi media sosial · pilihan ganda"/></div>}
   {(view==='Profil responden'||view==='Eksplorasi jawaban')&&<div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Seberapa penting budaya kerja?</h2><p>Distribusi skor kepentingan · Q5</p></div></div><div className="rating-chart">{[1,2,3,4,5].map(score=>{const c=filtered.filter(r=>r.importance===score).length;return <button key={score} aria-pressed={filters.importance===String(score)} onClick={()=>toggle('importance',String(score))}><b>{c}</b><div><span style={{height:`${percent(c,n)}%`}}/></div><span>Skor {score}</span></button>})}</div><div className="chart-note">Rata-rata dihitung dari respons dengan skor terisi.</div></section><Bars field="research" title="Riset sebelum melamar" subtitle="Pernah mencari informasi perusahaan · Q2"/></div>}
   {(view==='Eksplorasi jawaban'||view==='Ringkasan')&&<div className="two-col"><Bars field="content" title="Konten yang membantu memahami tempat kerja" subtitle="Pilihan konten yang paling membantu · satu jawaban"/><section className="insight-panel"><span className="eyebrow">DARI JAWABAN RESPONDEN</span><MessageSquare size={31}/><h2>Gambaran nyata.<br/>Dari suara mereka.</h2><p>Baca apa yang menurut responden masih perlu ditampilkan perusahaan tentang kehidupan kerja.</p><div className="quote">“{filtered.find(r=>r.feedback.length>30)?.feedback||filtered[0].feedback||'Tidak ada jawaban tertulis.'}”</div><button onClick={()=>setView('Suara responden')}>Lihat semua jawaban <ArrowRight size={17}/></button></section></div>}
   {view==='Suara responden'&&<section className="panel feedback-panel"><div className="panel-head"><div><h2>Apa yang masih perlu ditampilkan perusahaan?</h2><p>Jawaban asli responden · Q8</p></div><label className="search-input"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari dalam jawaban..." aria-label="Cari jawaban"/></label></div><div className="feedback-list">{filtered.filter(r=>r.feedback.toLowerCase().includes(query.toLowerCase())).map(r=><article key={r.id}><div><span>R{String(r.id-1).padStart(3,'0')}</span><small>{label(r.status)}</small></div><p>{r.feedback||'Tidak ada jawaban.'}</p></article>)}{!filtered.some(r=>r.feedback.toLowerCase().includes(query.toLowerCase()))&&<p>Tidak ada jawaban yang cocok dengan pencarian.</p>}</div></section>}
   </>}
   <footer><span>Sumber: Employee Branding Survey · {rows.length} respons</span><span>Pilihan ganda: persentase dapat berjumlah lebih dari 100%.</span></footer>
  </div></main>
  {method&&<div className="modal-backdrop" onClick={()=>setMethod(false)}><section role="dialog" aria-modal="true" aria-labelledby="method-title" className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setMethod(false)} aria-label="Tutup"><X/></button><h2 id="method-title">Tentang data survei</h2><p><b>Sumber:</b> {survey.source}</p><p><b>Sheet:</b> {survey.sheet}. Satu baris adalah satu respons; sheet pivot tidak digabung agar respons tidak terhitung dua kali.</p><p><b>Periode:</b> 17–21 September 2026, berdasarkan timestamp pada Excel. Data merupakan snapshot dari file yang diberikan.</p><p><b>Perhitungan:</b> Q3, Q4, dan Q6 adalah pilihan ganda. Setiap pilihan dihitung maksimal sekali per responden. Persentase menggunakan jumlah responden setelah filter; total dapat melebihi 100%.</p><p><b>Interaksi:</b> Klik pilihan yang sama untuk menghapus filter. Filter berbeda digabungkan dengan kondisi DAN. Angka ringkasan serta semua chart mengikuti filter aktif.</p><p><b>Skor budaya:</b> rata-rata jawaban Q5, bukan skor kepuasan karyawan. ID R001 dan seterusnya dibuat dari urutan baris sumber.</p><button className="red-button" onClick={()=>setMethod(false)}>Mengerti</button></section></div>}
 </div>
}
